name: Terraform Plan - UAT

on:
  push:
    branches:
      - features/uat2

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Preprod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plans
        run: terraform plan -var-file="terraform.tfvars"
